name: CI/CD Pipeline for PetClinic

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build WAR using Maven
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gitpetclinic-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitpetclinic-app:latest

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gitpetclinic-app:latest

          docker network create petclinic-net || true

          docker rm -f mysql || true
          docker run -d \
            --name mysql \
            --network petclinic-net \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=petclinic \
            -e MYSQL_USER=petclinic \
            -e MYSQL_PASSWORD=petclinic \
            -p 3306:3306 \
            mysql:latest

          docker rm -f petclinic-app || true
          docker run -d \
            --name petclinic-app \
            --network petclinic-net \
            -p 8080:8080 \
            ${{ secrets.DOCKERHUB_USERNAME }}/gitpetclinic-app:latest
